services:
  shabat-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Jerusalem
    platform: linux/amd64
    restart: always
    volumes:
      - ./app:/app  
    ports:
      - "8080:80"  
